services:
  postgres:
    image: postgres:15
    container_name: flybooker-db
    environment:
      POSTGRES_DB: flybooker
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    image: g4rvr/flybooker:latest
    container_name: flybooker-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/logs
    restart: on-failure

volumes:
  postgres_data:
