services:
  postgres:
    image: postgres:15
    container_name: flybooker-db
    environment:
      POSTGRES_DB: flybooker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    image: g4rvr/flybooker:latest
    container_name: flybooker-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flybooker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8081:8081"

volumes:
  postgres_data:
